### PR TITLE
fix use namespace for LaravelIntegration

### PR DESCRIPTION
**Pull request by jeremytubbs**

### CODE REVIEW

**Comment by neomerx** [comment]
Thanks for noticing namespace issue. I've fixed issues with your PR and it should be all good in `master` branch.

**Comment by jeremytubbs** [comment]
Thanks for all your work... it is much appreciated.

**Comment by neomerx** [comment]
np mate
I'm working on adding Basic Auth, JWT Auth and CORS (it's actually done in feature branch I'm going to publish today) + ember client app.
It needs some enhancements in ember client (I'm a complete noob there) and in CORS (I'm comfortable there).

**Comment by neomerx** [comment]
It's gonna be :bomb: I feel very exited :smile:

**Pull request closed without merging**
